name: Vercel Production Deployment

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches:
            - Challenge_8-(FE)

jobs:
    Deploy-Production:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.11.1'

            - name: Install Yarn
              run: npm install --global yarn@latest

            - name: Clean Yarn Cache
              run: yarn cache clean

            - name: Remove Node Modules
              run: rm -rf node_modules

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            # - name: Run Build
            #   run: yarn run build
            #   with: 
            #     path: .vercel/output

            - name: Install Vercel CLI
              run: yarn global add vercel@latest

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
